Move snapshot/deletion code into functions

diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -42,6 +42,48 @@ EOM
   exit 1
 }
 
+create_snapshot() {
+  mkdir -p "$SNAPSHOT_DIR"
+
+  local -ar existing_snapshots=("${SNAPSHOT_DIR}/${PREFIX}"*)
+
+  local snapshot_dir
+  for snapshot_dir in "${existing_snapshots[@]}"; do
+    if [[ ! -d "$snapshot_dir" ]]; then
+      echo "$snapshot_dir is not a valid directory, aborting"
+      exit 1
+    fi
+  done
+
+  local -r new_snapshot_dir="${SNAPSHOT_DIR}/${PREFIX}$(date --iso-8601=seconds)"
+
+  echo "Creating snapshot $new_snapshot_dir"
+  mkdir "$new_snapshot_dir"
+
+  # The output redirection below simply swaps stdout and stderr so that we can
+  # filter cp's stderr output. After that's filtered we swap stdout and stderr
+  # again to restore the original stdout and stderr
+  cp -a --reflink=always -x "$SRC_DIR"/* "$new_snapshot_dir/"
+  rm -f "$LATEST_SYMLINK"
+  ln -s "$(basename "$new_snapshot_dir")" "$LATEST_SYMLINK"
+  echo "Done"
+}
+
+delete_old_snapshots() {
+  local -ar all_snapshots=("${SNAPSHOT_DIR}/${PREFIX}"*)
+
+  local -ir num_to_remove=$((${#all_snapshots[@]} - $COUNT))
+  if [[ $num_to_remove -gt 0 ]]; then
+    local -a sorted_snapshots
+    readarray -td '' sorted_snapshots < <(printf '%s\0' "${all_snapshots[@]}" | sort -z)
+    for remove_snapshot in "${sorted_snapshots[@]:0:$num_to_remove}"; do
+      rm -rf "$remove_snapshot"
+      echo "Removed snapshot $remove_snapshot"
+    done
+  fi
+}
+
+
 declare -i COUNT=0
 declare -i DRY_RUN=0
 
@@ -91,43 +133,5 @@ fi
 declare -r LATEST_SYMLINK="$SNAPSHOT_DIR/latest"
 
 
-# Create snapshots
-
-mkdir -p "$SNAPSHOT_DIR"
-
-declare -ar existing_snapshots=("${SNAPSHOT_DIR}/${PREFIX}"*)
-
-for snapshot_dir in "${existing_snapshots[@]}"; do
-  if [[ ! -d "$snapshot_dir" ]]; then
-    echo "$snapshot_dir is not a valid directory, aborting"
-    exit 1
-  fi
-done
-
-declare -r new_snapshot_dir="${SNAPSHOT_DIR}/${PREFIX}$(date --iso-8601=seconds)"
-
-echo "Creating snapshot $new_snapshot_dir"
-mkdir "$new_snapshot_dir"
-
-# The output redirection below simply swaps stdout and stderr so that we can
-# filter cp's stderr output. After that's filtered we swap stdout and stderr
-# again to restore the original stdout and stderr
-cp -a --reflink=always -x "$SRC_DIR"/* "$new_snapshot_dir/"
-rm -f "$LATEST_SYMLINK"
-ln -s "$(basename "$new_snapshot_dir")" "$LATEST_SYMLINK"
-echo "Done"
-
-
-# Delete old snapshots
-
-declare -ar all_snapshots=("${SNAPSHOT_DIR}/${PREFIX}"*)
-
-declare -ir num_to_remove=$((${#all_snapshots[@]} - $COUNT))
-if [[ $num_to_remove -gt 0 ]]; then
-  declare -a sorted_snapshots
-  readarray -td '' sorted_snapshots < <(printf '%s\0' "${all_snapshots[@]}" | sort -z)
-  for remove_snapshot in "${sorted_snapshots[@]:0:$num_to_remove}"; do
-    rm -rf "$remove_snapshot"
-    echo "Removed snapshot $remove_snapshot"
-  done
-fi
+create_snapshot
+delete_old_snapshots
